[package]
name = "transliterator-ferris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.24.1", features = ["derive"] }
lazy_static = "1.4.0"
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = { version = "1.0.93" }